### PR TITLE
[Masterminds#82] Added FROM clause to update builder

### PR DESCRIPTION
**Pull request by mlaflamm**

### CODE REVIEW

**Comment by Kegley** [comment]
Any updates on this PR?

**Comment by Sibley199** [comment]
Any update on this PR? Would be super useful to get this merged in if accepted

**Comment by mlaflamm** [comment]
To be honest, we gave up on on `squirrel` shortly after submitting this PR. We are now using [go-jet](https://github.com/go-jet/jet), a typesafe query builder with code generation. We have use it for about a year in multiple projects and we love it. 

I wrote a [gist](https://gist.github.com/mlaflamm/5093c5877b401f608a1a737fab7b662c) explaining how we customise some of the generated data types.

**Comment by ysomad** [comment]
Any update on this?

**Comment by yazver** [comment]
Why hasn't it been merged until now?

**Pull request merged**
