### PR TITLE
[#60] Added limit all method

### PR DESCRIPTION
**Pull request by sivagollapalli**
#60 Added limit all function to select builder

### CODE REVIEW

**Comment by lann** [comment]
Is there any advantage to `LIMIT ALL` vs omitting the LIMIT entirely? I wonder if something like `ResetLimit` that just removes the "Limit" entry would be more clear to people.

**Comment by sivagollapalli** [comment]
@lann Do you mean `ResetLimit()` would be more self-explanatory rather `LimitAll()`?

**Comment by lann** [comment]
I think so, or maybe `RemoveLimit`? `LIMIT ALL` is pretty obscure SQL syntax since it appears to be equivalent to omitting LIMIT entirely.

**Comment by sivagollapalli** [comment]
@lann Made changes. Could you please check?

**Pull request merged**
