### PR TITLE
Add lk and nlk condition expressions.

### PR DESCRIPTION
**Pull request by limoli**
As my feature/issue #122 , I think it could be an useful feature for LIKE operations.

### CODE REVIEW

**Comment by Limoli** [comment]
Any news about it?

**Comment by lann** [comment]
Sorry I didn't look at this previously. This looks good and I'm inclined to merge. Two questions:
1. `Lk` seems a little obscure for saving 2 characters. How would you feel about `Like` and `NotLike`?
2. Is it possible to collapse some of the common logic between Lk.ToSql and Eq.ToSql? I haven't looked too closely, so "no" is a perfectly good answer.

**Comment by limoli** [comment]
Yes, sure!
1. I used `Lk` and `NotLk` because I followed the conventions of your project. So, I totally agree about the renaming. It's much better.
2. I think that it could be possible, but an abstraction is needed and it could take little time. So, in my opinion, we can keep this pull for now with the renaming and think about a collapse of logics/abstraction later.

**Comment by lann** [comment]
Thanks!

**Comment by limoli** [comment]
Your welcome :)

**Comment by ivanjaros** [comment]
I would like to have this feature but it is missing from master. Is v1 considered "prod" instead of master?

**Comment by ivanjaros** [comment]
@limoli the gopkg repo does not have this commit and v1 github repo does not exist(obviously).

**Pull request merged**
