### PR TITLE
Added stringer to select builder

### PR DESCRIPTION
**Pull request by sivagollapalli**
#64

### CODE REVIEW

**Comment by sivagollapalli** [comment]
@lann Currently I have added to `SelectBuilder`. Let me know am I in the right path. So I would go ahead and add to remaining builders. 

Out of curiosity, I feel it is duplicating the same code since `ToSql` and `String` returns same `sql` string. Could you let me know what would be the use case where devs would prefer to use `String` over `ToSql`? Please pardon me if I ask a very basic question.

**Comment by lann** [comment]
The only advantage would be for debugging, though I'm not actually sure this should be added at this point since it could change output for some existing programs

**Comment by sivagollapalli** [comment]
@lann Could we ignore this change since it might change the output of certain programs?

**Comment by lann** [comment]
We can ignore it. The request for it is quite old and I happen to know that the requestor probably doesn't care any more.

**Pull request closed without merging**
