### PR TITLE
Implements Union and UnionAll on SelectBuilder.

### LINKED ISSUE #20: Add UNION operator
I want to express query `SELECT a FROM b WHERE col>? UNION SELECT a FROM c WHERE col<?` but squirrel is not supporting `UNION`.

I think, The following example code is good design for support `UNION`.

``` go
q, attrs, err := sq.Union(
        sq.Select("*").From("a").Where("col > ?", hoge),
        sq.Select("*").From("b").Where("col < ?", piyo)).ToSql()

q == "SELECT a FROM b WHERE col>? UNION SELECT a FROM c WHERE col<?"
attrs == []interface{hoge, piyo}
```

What do you think so?  If you agree on this idea, I'll create patch and send PR.
Thanks!

### PR DESCRIPTION
**Pull request by wI2L**
Close #20.

### CODE REVIEW

**Comment by wI2L** [comment]
shamelessly took the work of @umisama from https://github.com/Masterminds/squirrel/issues/20 and tried it again v1 HEAD on my project, it works perfectly.

@Iann you requested a proper PR (https://github.com/Masterminds/squirrel/issues/20#issuecomment-340580579), here it is. Im willing to tackle any issue/comments you or others would have with it.

**Comment by lann** [comment]
Hmm...this implementation doesn't match the initial proposal in #20 (`sq.Union(select1, select2)`) and doesn't seem to provide much benefit over using `Suffix` as I suggested there. Concerns:

* This doesn't provide a way to ORDER BY/LIMIT the complete union, e.g. `(SELECT 2 AS x) UNION (SELECT 1 AS x) ORDER BY x`
* The ordering of UNIONs matters, and if you try to mix calls to `Union` and `UnionAll` they may be reordered.

If you're willing to address these issues that would be great, otherwise I'll probably take another look eventually.

**Comment by wI2L** [comment]
> Hmm...this implementation doesn't match the initial proposal

Actually, the original author didn't followed the proposal of `sq.Union(select1, select2)` in his PR. The `Union` and `UnionAll` methods were attached to `SelectBuilder`, and I followed that. I do, however, would myself prefer the way you propose.

- I have indeed noticed some flaws while testing the code myself. `OrderBy` works, but since it has to be attached to the `SelectBuilder` that is after the `Union` clause, this is bad for comprehension.
- I think the ordering issue should be fixed if we use a specific `Sqlizer` type for union instead of using a a method directly on `SelectBuilder`.

I'll work to improve the PR based on your recommendations. Thanks for the quick response.

**Comment by lann** [comment]
Note that for ordering across a UNION you have to put the SELECTs in parens as in `(SELECT 2 AS x) UNION (SELECT 1 AS x) ORDER BY x`

**Comment by wI2L** [comment]
Right.
What do you expect as implementation ?
`sq.Union` returning an `SelectBuilder` or a `Sqlizer` ?
If we with `Union(builder ...SelectBuilder) Sqlizer`, then the `GroupBy` and `PlaceholderFormat` would have to be added to the underlying type.
However if we return a `SelectBuilder`, one could construct wrong statement like `sq.Select("*").From("b").Union(select1,select2)`. I don't think this is desirable.

How I see it, correct me if I'm wrong, the `sq.Union` function would be just a wapper around `SelectBuilder` that adds the required methods like `GroupBy`, `PlaceholderFormat`, and others that I don't think about.

**Comment by lann** [comment]
Ugh, good points. I think I'm remembering why I haven't worked on this before...

I think the only sane way to handle this is a new `UnionBuilder` type with methods like `Union`, `UnionAll`, `OrderBy`, etc.

**Comment by wI2L** [comment]
@lann I'm fine with it, at least it will prevent wrong usage.

I have used the implementation you proposed in issue #20 in the meantime, it works, but it's not really clear.

- The `PlaceholderFormat` has to be used on the `SelectBuilder` on which `Suffix` is called and not the other one, or the final query will have conflicting placeholders.
- Adding an `ORDER BY` clause also require to concatenate it at the end of the final SQL query.
- To order accross UNION, I have to manually enclose the query between ().

Last thing, what do you think of preventing the usage of `Union` and `UnionAll` at the same time ? It looks wrong to me.
`sq.Union(select1,select2).UnionAll(select3,select4).OrderBy(...)` would result in `(select1) UNION (select2) ?? (select3) UNION ALL (select4) ORDER BY ...`. How the two UNION/ALL clauses would be used together ? 
Instead of that, I'd go with a generic UNION builder implementation (codewise), with a configurable clause, so we don't have to duplicate code for `UnionBuilder` and `UnionAll` builder.

**Comment by lann** [comment]
I would expect that to be `(select1) UNION (select2) UNION ALL (select3) UNION ALL (select4)`. I think it makes sense to have a generic clause + a shortcut for at least "UNION". There are other less common compound SELECT clauses like INTERSECT: https://www.sqlite.org/syntax/compound-select-stmt.html

**Comment by wI2L** [comment]
@lann So I gave it a though today. The implementation of a generic `SetBuilder` that would support the clauses `UNION [ALL]`, `INTERSECT [ALL]` and `EXCEPT [ALL]` seems a bit more subtil to me.

If we provide an implementation of the `Builder` type, with methods `Union()`, `UnionAll()`, `Intersect()` that would use the underlying `Builder` methods like `Append` to store the `SelectBuilder`, it will be impossible to reconstruct the query properly because we will loose the original ordering of the clauses.

For example, if we had the ability to do:
```go
sq.Union(select1,select2).UnionAll(select3).Except(select4)
```
the builder implementation will have two Union parts, one UnionAll part and one Except part, but once the method `ToSql()` is called, it doesn't know in which order it have to put the parts into the final query.

**What I propose instead is the following.**

## **PROPOSAL 1**

Let say we have a private type `SetBuilder` that implements the `Sqlizer` interface.
```go
type SetBuilder struct {
    Clause string
    Args   []interface{}
}

func (s SetBuilder) ToSql() (string, interface{}, err) {}
```

A `SetBuilder` would be created using a dedicated constructor for each Set clause that the SQL spec offer. The constructors will take a variadic list of `interface{}` as single parameter.
```go
func Union(args ...interface{}) SetBuilder {
    return SetBuilder{clause: "UNION", args: args}
}
func UnionAll(args ...interface{}) SetBuilder {
    return SetBuilder{clause: "UNION ALL", args: args}
}
// and so on for all the other Set clauses.
```
The SetBuilder type will also have methods like `GroupBy`, `Prefix()`, `Suffix()`, `Limit()`, `Offset()`, `PlaceholderFormat`... (maybe others may apply ?).
This will allow to write simple, yet comprehensive code as:
```go
sq.Union(select1,select2).GroupBy(x).PlaceholderFormat(sq.Dollar).ToSql()
```

However, this doesn't solve everything. With the above proposal, it would be impossible to combine different Set clauses to achieve something like `select1 UNION select2 EXCEPT select3 INTERSECT select4`.
This is why I think the `SetBuilder` constructors should accept a variadic list of interface. We could accept both the `SelectBuilder` type and `SetBuilder` itself (type assert, anything else will be treated as an error). This way, one could write something like:
```go
sq.Union(select1, sq.UnionAll(select2, select3), sq.Except(select4, select5)).ToSql()
// (select1) UNION (select2 UNION ALL select3) UNION (select4 EXCEPT select5)
```
Since the SetBuilder returned by `sq,Union` will have stored the variadic args with the order they are declared, the final query is consistent.
Note that using a single `SelectBuilder` argument in the parameters list of a `SetBuilder` constructor would allow be valid:
```go
sq.Intersect(sq.Union(select1)).ToSql()
// select1
sq.Intersect(sq.Union(select1), select2)
// select1 INTERSECT select2
sq.Intersect(sq.Union(select1, select2), select3)
// (select1 UNION select2) INTERSECT select3 
```

Moreover, we could prevent some errors when building the final SQL query.
Let say we have this statement:
```go
sq.Union(select2, sq.Except(select2, select3).GroupBy(x)).GroupBy(a).ToSql()
```
The use of `OrderBy` on the `SetBuilder` returned by `sq.Except` is invalid since the clause must appear once at the end of the final query only, but since the `ToSql()` method will be called on the `SetBuilder` returned by `sq.Union`, we could simply access the exported fields of the `SetBuilder` returned by `sq.Except` to construct the query instead on relying on its `ToSql` method. This way, any `GroupBy` clause attached to the `sq.Except` builder, or prefix/suffix will be ignored (prefix with `WITH` would be illegal here anyway).

## **PROPOSAL 2**

Based on the propositions of proposal 1, we could also take a slighly different approach.
Instead of using the `SetBuilder` type as builder, it could be simply a type with no methods, called `Set` that would just hold a list of `SelectBuilder`.
Some code to explain it will be simpler:

```go
type set []SelectBuilder

type Union set
type UnionAll set
type Except set
// and so on for other clauses

// We provide a SetBuilder type to combine the above type together

type SetBuilder struct{
   sets []set
}
// implements Sqlizer interface
func (s SetBuilder) ToSql()

func NewSet(sets ...set) SetBuilder {}
```
The usage would looks like:
```go
query := sq.NewSet(sq.Union{select1, select2, sq.Except{select3, select4}}).ToSql()
/// select1 UNION select2 UNION (select 3 EXCEPT select4)
```

With the above, we can achieve the same result as in the proposal 1.
The methods like `Suffix`, `Prefix` and so on would be attached to the `SetBuilder` type.
With this second proposal, since the "sets" types `Union`, `Except`, ... are simply responsible for holding a list of `SelectBuilder` and does not carry any specific methods, an errorneous statement like the following (take from proposal 1) is not possible.
```go
sq.Union(select2, sq.Except(select2, select3).GroupBy(x)).GroupBy(a).ToSql()
```
but will become
```go
query := NewSetBuilder(sq.Union{select1, sq.Except{select2,select3}}).GroupBy(a).ToSql()
```

**NOTE:** When building the query from a `SetBuilder`, parenthesis would be used to ensure that the priority of clauses is respected based on the declaration since UNION and EXCEPT and equal precedence, but INTERSECT does not.


------

Sorry for the very long post, I just throw all my ideas and thoughts at once. Don't hesistate to criticize things that looks weird to you. I tend to think that the proposal 2 is better IMHO because it prevent user to write code that would generate bad query.

Types naming could also be refined.

William

**Comment by lann** [comment]
`Append` and `Extend` preserve order (using an underlying `ps.List`). `Set` does not (`ps.Map`).

Two of the main design ideas for Squirrel's API are:

1. Persistent data structures allow reusing query fragments, e.g.:

    ```go
    baseSelect = sq.Select("some", "columns")
    select1 = baseSelect.From("table1") // SELECT some, columns FROM table1
    select2 = baseSelect.From("table2") // SELECT some, columns FROM table2
    ```

    This requires that the builder methods do not mutate their structs, which is why they all return a new Builder.

2. Make the Go look as much like the resulting SQL as reasonably possible.

    This is more subjective, but I have tried to make the API read like SQL with some extra punctuation, so e.g. `sq.Select("*").From("table") == "SELECT * FROM table"`.

I would probably design this something like (totally untested):

```go
type unionSelect struct {
    op string // e.g. "UNION"
    select SelectBuilder
}

type unionData struct {
    // PlaceholderFormat?
    FirstSelect SelectBuilder
    UnionSelects []*UnionSelect
    OrderBys []string
    Limit string
    Offset string
    // Suffixes?
}

func (d *unionData) toSql() (string, []interface{}, error) {
    // pseudocode:
    // sql, _, _ = d.FirstSelect.ToSql()
    // for _, us := range d.UnionSelects
    //    sql += us.op + "(" + us.select + ")"
}

type UnionBuilder builder.Builder

func (b UnionBuilder) Select(operator string, select SelectBuidler) UnionBuilder {
    return builder.Append(&unionSelect{op: operator, select: select}).(UnionBuilder)
}

func (b UnionBuilder) Union(select SelectBuilder) UnionBuilder {
    return b.Select("UNION", select)
}

// select.go

func (b SelectBuilder) Union(select SelectBuilder) UnionBuilder {
    return UnionBuilder(builder.EmptyBuilder).Set("FirstSelect", b).(UnionBuilder).Union(select)
}
```

This enables an API like:

```go
select1 = sq.Select("id", "name").From("table1")
select2 = sql.Select("id", "name").From("table2")
union = select1.Union(select2)
```

**Comment by jdeal-mediamath** [comment]
Any progress on this? Would be really nice to have Union support.

**Comment by jnvillar** [comment]
this code is not in master, did you remove it?

**Comment by lann** [comment]
> will this be merged any time soon?

Not in its current state.

**Pull request closed without merging**
