### PR TITLE
modified NotEq to use "!=" instead of "<>"

### PR DESCRIPTION
**Pull request by Itshardtopickanusername**

### CODE REVIEW

**Comment by Itshardtopickanusername** [comment]
I'm not sure why the build is failing. I checked and noticed that last few PRs are failing the same way for Go versions 1.12 and 1.11

**Comment by lann** [comment]
What is the reason for this change? As I understand, these are equivalent in most databases and in fact `<>` is part of ANSI SQL while `!=` is not.

**Comment by Itshardtopickanusername** [comment]
main reason why I looked into this was because, I'm using squirrel for SOQL (Salesforce Object Query Language) which is extremely close to the regular SQL. After looking into the documentation for it, Salesforce suggests to use '!=' which is also compatible with PostgreSQL/MySQL. the diamond operator does indeed seem to work in SOQL as well, but per their docs, they use '!='. I commented the suggestion to replace '<>' with '!=' in the source code and somebody replied to create a pull request for this change.

**Comment by lann** [comment]
I'm not inclined to merge this. While it should be fine for most users, it is likely to break at least some downstream tests, and doesn't seem worth it for essentially an aesthetic change. You might consider just forking this repo; the library is essentially in maintenance-only mode and unlikely to get any updates that would benefit SOQL.

**Comment by Itshardtopickanusername** [comment]
Understandable! thank you for considering it.

**Pull request closed without merging**
