### PR TITLE
allow 3rd party wrappers to be used as runners.

### PR DESCRIPTION
**Pull request by james-lawrence**
found this useful in my projects, can be used to remove the explicitly checking for sql.DB and sql.TX

### CODE REVIEW

**Comment by lann** [comment]
This seems so obvious that I feel like I must be missing something. Why didn't I do this before...

**Comment by james-lawrence** [comment]
sure, threw this together in github so I need to format it properly anyways =p

**Comment by james-lawrence** [comment]
changes done

**Comment by lann** [comment]
Thanks!

**Pull request merged**
